inherit_from:
  - .rubocop_todo.yml
  - https://relaxed.ruby.style/rubocop.yml



require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - spec/dummy/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - spec/features/**/*

Metrics/BlockLength:
  Enabled: false

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
